-- 코드를 입력하세요
WITH CP AS (
    SELECT CAR_TYPE, CAST(DISCOUNT_RATE AS UNSIGNED) AS R
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT 
    CC.CAR_ID,
    CC.CAR_TYPE,
    ROUND(CC.DAILY_FEE * 30 * (100 - CP.R) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CP
    ON CC.CAR_TYPE = CP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단', 'SUV')
  AND CC.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
  )
  AND ROUND(CC.DAILY_FEE * 30 * (100 - CP.R) / 100) >= 500000
  AND ROUND(CC.DAILY_FEE * 30 * (100 - CP.R) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;