-- 코드를 작성해주세요
SELECT
II2.ITEM_ID, II2.ITEM_NAME, II2.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO II
ON IT.PARENT_ITEM_ID = II.ITEM_ID
JOIN ITEM_INFO II2
ON IT.ITEM_ID = II2.ITEM_ID
WHERE II.RARITY = 'RARE'
ORDER BY II2.ITEM_ID DESC