-- 코드를 작성해주세요
SELECT ED.ID, ED.GENOTYPE, PARENT_ED.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA ED
JOIN ECOLI_DATA PARENT_ED
ON ED.PARENT_ID = PARENT_ED.ID
WHERE PARENT_ED.GENOTYPE & ED.GENOTYPE = PARENT_ED.GENOTYPE
ORDER BY ED.ID